### ISSUE TITLE
HOT: Create basic method for working with messages (messageService)

### ISSUE THREAD

**Issue by olisikh** [Lisikhs/geronimo-api#4]
The service needs to return posts on demand. This service should support next operations:

1. postMessage - send a message
2. retweetMessage - retweet message to make it showable in your feed
3. answerMessage - should add a reply to a message
4. countLikes
5. countReblogs

the service should use messageDAO to work with messages, and service should be transactional.

**Comment by artemlisikh** [comment]
#8 pull request corresponds to this issue

**Comment by olisikh** [comment]
Well done!
